name: github_contributions
description: A library to get GitHub users' contributions information, for Dart and Flutter developers
version: 0.2.0
homepage: https://github.com/pd4d10/github-contributions
author: Rongjian Zhang <pd4d10@gmail.com>

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  http: ^0.12.0
  html: ^0.14.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
